# Generated by Django 3.1.1 on 2020-09-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='created')),
            ],
            options={
                'ordering': ('-created',),
                'get_latest_by': '-created',
            },
        ),
    ]
